app/models.py
from flask_login import UserMixin
from .import login_manager
from . import db
from werkzeug.security import generate_password_hash,check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User (UserMixin,db.Model):
    """ User model """

    __tablename__ = "users"
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    password_secure = db.Column(db.String(255))
    pitch = db.relationship('Pitches',backref = 'user',lazy = 'dynamic')
    comments = db.relationship('Comments',backref = 'user',lazy = 'dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_secure,password)





    def __repr__(self):
        return f'User {self.username}'

class Pitches (db.Model):
    """ Pitches model """

    __tablename__ = "pitches"
    id = db.Column(db.Integer,primary_key = True)
    category = db.Column(db.String(255),index = True)
    pitch = db.Column(db.String(255),unique = True,index = True)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comments = db.relationship('Comments',backref = 'pitch',lazy ='dynamic')



    def __repr__(self):
        return f'Pitches {self.pitch}'

class Comments (db.Model):
    """ Comments model """

    __tablename__ = "comments"
    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String(255),index = True)
    pitches_id = db.Column(db.Integer,db.ForeignKey("pitches.id"))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    category = SelectField('Pitch Category',choices=[('Technology','Technology'),('coding','coding'),('love','love'),('Happiness','Happiness')])
    pitch = TextAreaField('pitch')
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    comment = TextAreaField('Comment')
    submit = SubmitField('Post Comments')    

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from config import config_options


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):


    app = Flask(__name__)


    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')


    
    login_manager.init_app(app)


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)



    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors

app/main/views.py
from flask import Flask,render_template,redirect,url_for
from . import main
from flask_login import login_required,current_user
from .forms import PitchForm,CommentForm
from .. import db
from ..models import Pitches,User,Comments

@main.route('/')
def index():
    '''
    my index page
    '''
    title = 'Pitch It UP'
    return render_template('index.html',title = title)

@main.route('/pitch/', methods = ['GET','POST'])
@login_required
def new_pitch():

    form = PitchForm()

    if form.validate_on_submit():
        category = form.category.data
        pitch= form.pitch.data
        

        # Updated pitchinstance
        new_pitch = Pitches(category= category,pitch= pitch,user=current_user)

        db.session.add(new_pitch)
        db.session.commit()

        title='New Pitch'


        return redirect(url_for('main.index'))

    return render_template('pitch.html',pitch_entry= form)

@main.route('/categories/<cate>',methods = ['GET','POST'])
def category(cate):
    '''
    function to return the pitches by category
    '''


    form = CommentForm()
    
    
    pitches = Pitches.query.filter_by(category=cate).all()
    print(category)
    title = f'{cate}'
    return render_template('categories.html',title = title, pitches = pitches,comment_form = form)


@main.route('/all_comment/<int:pitches_id>', methods = ['GET', 'POST'])
@login_required
def all_comment(pitches_id):
    pitch = Pitches.query.filter_by(id=pitches_id).first()
    comments = Comments.query.filter_by(pitches_id=pitches_id).all()

    form = CommentForm()
    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comments(comment=comment,user=current_user,pitch=pitch)


        db.session.add(new_comment)
        db.session.commit()

       

        return redirect(url_for('categories.html',cate =pitch.category))


    
    return render_template('new_comment.html',comments= comments)
  

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Pitch it up</title>
    {% endif %}
</head>
<body>
    {% block content %}


    {% endblock %}
    
</body>
</html>

app/templates/categories.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block super %}{{ super ()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/categories.css')}}"> {% endblock %}
<br>
<br>
<br>
<br>

<body>
    {% block content %}
    <br>
    <br>
    
  <div class="container">
    <div class="card-columns">
      {% for pitch in pitches %}

      <div class="card bg-transparent border-success">
        <div class="card-header bg-transparent border-success">
  
        </div>
        <div class="card-body text">
          <blockquote class="blockquote mb-0">
            <p>{{pitch.pitch}}</p><br>
            <footer class="blockquote-footer bg-transparent border-success">{{pitch.user.username}}
              
          </blockquote>
        </div>
        <div class="card-footer bg-transparent border-success">
          {{wtf.quick_form(comment_form)}}
          <br>

          <button type="button" class="btn btn-outline-success btn-sm"><button type="button" class="btn btn-outline-success btn-sm"><a href="/all_comment/{{pitch.id}}">View comments</a></button></div>
      </div><br><br><br>

      {% endfor %}
      
    </div>
    {% endblock %}
</body>

app/templates/comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<br>
<br>
<div class="container">
<br>
<br>
  {% for comment in comments %}
  <Ul>
    <li>{{commment.comment}}</li>
  </Ul>

  {% endfor %}


</div>



{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% block styles%} {{ super() }}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
 {% endblock %}

{% block content %}

<body>
  <div class="container" style="width: 100%; height: 100%;">
    <div class="row"> 
        <br>
        <div class="col-md-12">
            <img src="/static/images/pitch.png" class="center">
        </div>
        <br>
        <br>
        <div class="col-md-12">
        <p style="font-size: 20px; float:left; color: gray;" > <strong> In life you only have 60 seconds to impress someone. 
        One minute to make or break you. How do we make sure that you use your one minute to actually say something meaningful ? </strong> </p>
        </div> 
    </div>
  
  <br>
  <div class="d-flex justify-content-center">
    <div class="card-groups">
      <div class="card border-info mb-5" style="width: 70rem;height: 20rem;background-color: transparent;">
        <div class="card-header">Technology</div>
        <div class="card-body text-info">
          <br>
          <br>
          <h5 class="card-title" style="color: darkgray;">Lets pitch about technology</h5>
          <p class="card-text">Add Technology pitches on best the way technology can be bring people together.</p>
          <button type="button" class="btn btn-outline-success"><a href="{{url_for('main.new_pitch')}}">Add Pitch</a></button>
          <button type="button" class="btn btn-outline-success"><a href="/categories/Technology">Read Pitches</a></button>
        </div>
      </div>

      <div class="card border-info mb-5" style="width: 70rem;height: 20rem;background-color: transparent;">
        <div class="card-header">Coding</div>
        <div class="card-body text-info">
          <br>
          <br>
          <h5 class="card-title">Coding pitches</h5>
          <p class="card-text">Talk is cheap.Show me the code.Add more coding pitches here.</p>
          <button type="button" class="btn btn-outline-success"><a href="{{url_for('main.new_pitch')}}">Add Pitch</a></button>
          <button type="button" class="btn btn-outline-success"><a href="/categories/coding">Read Pitches</a></button>
        </div>
      </div>

      <div class="card border-info mb-5" style="width: 70rem;height: 20rem;background-color: transparent;">
        <div class="card-header">Love</div>
        <div class="card-body text-info">
          <br>
          <br>
          <h5 class="card-title">Put down love Pitches here.</h5>
          <p class="card-text">Love recognizes no barries. Add more exicting pitches</p>
          <button type="button" class="btn btn-outline-success"><a href="{{url_for('main.new_pitch')}}">Add Pitch</a></button>
          <button type="button" class="btn btn-outline-success"><a href="/categories/love">Read Pitches</a></button>
        </div>
      </div>

      <div class="card border-info mb-5" style="width: 70rem;height: 20rem; background-color: transparent;">
        <div class="card-header">Happiness</div>
        <div class="card-body text-info">
          <br>
          <br>
          <h5 class="card-title">Happiness pitches</h5>
          <p class="card-text">Happiness is a direction,not a place.Add more happiness pitches.</p>
          <button type="button" class="btn btn-outline-success"><a href="{{url_for('main.new_pitch')}}">Add Pitch</a></button>
          <button type="button" class="btn btn-outline-success"><a href="/categories/Happiness">Read Pitches</a></button>
        </div>
      </div>
    </div>
  </div>
</div>
<style>
  .card-text{
    color: darkkhaki;
    font-size: medium;
    text-align: center;
  }
  .container{
    background-color: black;
    width: 100%;
    height: 100%;
  }
  .card-header{
    color: cadetblue;
    font-size: large;
    text-align: center;
  }
  .p{
    color: thistle;
  }  
  
</style>

  {% endblock%}
</body>

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: blanchedalmond;">
    <a class="navbar-brand" href="/">Lets start pitching.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        
      </ul>
      <ul class="nav navbar-nav navbar-right">

        {% if current_user.is_authenticated %}

        <li style="color:white;padding:15px;">{{current_user.username}}</li>
        
        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
        {%endif%}
      </ul>
   
      
  </nav>

app/templates/pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<br>
<br>
<div class="container">
<br>
<br>
  {{ wtf.quick_form(pitch_entry) }}


</div>



{% endblock %}